### ISSUE TITLE
Unable to build from repo

### ISSUE THREAD

**Issue by fbennett** [mangalam-research/salve#68] opened 2019-03-29 15:20 UTC
I don't use gulp much, and may be missing something. This is what I see, using `node` v8.9.1, `gulp` CLI v3.9.1, `gulp` local v4.0.0:
1. Clone the `salve` repo with `git`.
2. Run `npm install`
3. Run ` npm install -g gulp`
4. Run `gulp`
5. Boom

The error is:
``` text
[00:13:09] Using gulpfile /media/storage/src/JM/salve/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by fbennett** [comment] 2019-03-29 15:40
Poking around the Net, it looks like this may be an issue with the `node.js` version. What version is used for `salve` development?

**Comment by lddubeau** [comment] 2019-03-29 15:46
I use Node 10, but salve is tested on Node 8 and 10. (See [here](https://travis-ci.com/mangalam-research/salve-dom/builds/105889312).)

I think the issue is with gulp. To me it looks like the global gulp is v3 whereas the local one which salve requires is v4. AFAICT, a global v3 trying to run v4 does not work. The reverse works though. So if you use v4 *at all* your global install of gulp should be v4. If you don't want to upgrade your global gulp, you can always use `./node_modules/.bin/gulp`. Sometimes I do that with tools that call for using a globally installed utility but I don't want to install it.

**Comment by fbennett** [comment] 2019-03-29 16:21
Thanks. One more try got there. The system says that 4.0.0 gulp-cli does not exist. So I trashed global (and deleted a copy in /usr/bin that was there, but apparently not attached to anything the package manage knows about). Running from local now works. We'll see how it goes from here.

What I hope to do is remove a dependency on Java in this:

https://www.npmjs.com/package/citeproc-test-runner

Currently it uses jing to validate citation style definitions and return the result as a string. Do you know of a bundle that would do that, or would I need to build the infrastructure myself? Everything seems tightly bound to browser environments, but this needs to run in node.js.

**Comment by lddubeau** [comment] 2019-03-29 16:54
For the purpose you mention I'd use [saxes](https://github.com/lddubeau/saxes) to parse the XML and salve to validate it. There are some examples within salve's code-base that do just that:

* https://github.com/mangalam-research/salve/blob/develop/lib/salve/parse.ts

* https://github.com/mangalam-research/salve/blob/develop/test/validation.js

* https://github.com/mangalam-research/salve/blob/develop/lib/salve/conversion/parser.ts

The first example is probably the one which is closest to a general-purpose command line tool. The last example is highly idiosyncratic to salve's internal needs and probably not very useful as a general example. I never got around to producing such a tool based on salve and saxes because most uses of salve are in browser-based tools that use the DOM to perform the job that saxes would do.

Note that the first example (and probably the others too) attempts to load a RelaxNG scheme first as a JSON file (`readTreeFromJSON`) which needs to be pre-generated, then they try to load the RelaxNG as XML (`convertRNGToPattern`). The simplest thing to do in general is to just feed the RelaxNG to `convertRNGToPattern` and ignore `readTreeFromJSON/writeTreeToJSON`. `readTreeFromJSON` can be useful in cases where it makes sense not to pay for the cost of running `convertRNGToPattern` over and over. In such cases, `writeTreeToJSON` can be used to cache the internal representation of the RNG and then load that later instead of reparsing and resimplifying the original RNG, which can be costly for large RNG files.

I'm going to close this since the issue was really how gulp was setup on your machine and not an issue with salve itself, but let me know if I can help further.

**Closed as completed by lddubeau** 2019-03-29 16:54 UTC
Labels: question

**Comment by fbennett** [comment] 2019-03-29 22:37
Yes indeed - and many thanks for your guidance on both issues.
